a = 3
b = 3
suma = a + b
print("suma = ", suma)
resta = a - b
print("resta = ", resta)
multi = a * b
print("Multiplicacion = ", multi)
division = a / b
print("Division = ", division)
modulo = a % b
print("modulo = ", modulo)
exponente = a ** b
print("exponente = ", exponente)
